export const GET_ENVIRONMENT = "GET_ENVIRONMENT";
export const LOAD_DASHBOARD = "LOAD_DASHBOARD";
export const NOTIFY_ERROR = "NOTIFY_ERROR"
export const ENVIRONMENT_CHANGE = "ENVIRONMENT_CHANGE";
export const GET_SERVICES = "GET_SERVICES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";
export const GET_SERVICES_LOG = "GET_SERVICES_LOG";



